service: delfosti-carlosar

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
  obtenerProducto:
    handler: handler.obtenerProducto
    events:
      - http:
          method: GET
          path: /obtenerproducto/{id}
  actualizarProducto:
    handler: handler.actualizarProducto
    events:
      - http:
          method: PUT
          path: /actualizarproducto
  crearProducto:
    handler: handler.crearProducto
    events:
      - http:
          method: POST
          path: /crearproducto
  borrarProducto:
    handler: handler.borrarProducto
    events:
      - http:
          method: DELETE
          path: /borrarProducto
  busqueda:
    handler: handler.busqueda
    events:
      - http:
          method: GET
          path: /buscar/{fraccionpalabra}